name = "liquidterminal-front"
compatibility_date = "2025-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_ENVIRONMENT = "production"
NEXT_PUBLIC_API = "https://liquidterminal.up.railway.app"
NEXT_PUBLIC_PRIVY_AUDIENCE = "cm4cl0h2003xd10qwvd8w53wz"
